name: "build"
on:
  push:
    branches:
      - main

jobs:
  build-binksi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install, build ink, build website
      run: npm install && npm run dendry make-html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: online-editor # The branch the action should deploy to.
        folder: out/html # The folder the action should deploy.
    